### PR TITLE
Add Elixir port

### PR DESCRIPTION
**Pull request by fluxgame**
Needed a utility like this in an Elixir project, so I worked up a quick port. If all looks good, after merge I'll submit to hex.pm.

### CODE REVIEW

**Comment by EamonNerbonne** [comment]
Neat! I'm traveling ATM, so I'll take a peak at this tomorrow.

**Review by EamonNerbonne — APPROVED** [review]
Looks good!

I note that you're using a different dictionary serialization than the JS+C# versions.  I presume you did so out of practicality?  One consequence thereof is that I can't easily recreate the dictionary, should common usage ever evolve (I've only ever updated the dictionary a handful of times, but it's not entirely static largely due to new acronyms and shorthands that often don't obviously follow normal english pronunciation rules).

I once decided to use a base-36 dict because it was a way to trivially compress the dictionary for in-browser usage, but perhaps that was a little bit on the "overly clever" side.  Alas.

I'm fine with merging the plain-old-elixir syntax dictionary, assuming that your preference.

If I ever update the dict (or somebody else does), should I try and remember to ping your github account?

I note that I've been slightly impolite by forgetting to update the readme with the authorship of contributed versions, but that's out of laziness - should I link to your github profile there?

Final formality: you're OK with (and allowed to) license this contents of this PR to me under the apache 2.0 license (https://github.com/EamonNerbonne/a-vs-an/blob/master/LICENSE)?

**Comment by fluxgame** [comment]
Ahh, I de-serialized the JSON file from the Python version into the Elixir map I'm using here, as that was easier than porting the base-36 deserializer as well. But, I can update to use the base-36 encoded dictionary, for consistency sake. I'll try to do that today.

Apache-2.0 is fine for licensing (I did write this in the context of work, but got permission to contribute it back); I noted that in the `mix.exs` file, which will be used when publishing to hex.pm.

**Comment by fluxgame** [comment]
Whew, that stretched my brain a bit. Fun problem though. This implementation uses the same base-36 encoded string as the others and processes it at compile time into the same map I was working with before.

**Comment by fluxgame** [comment]
Published!: https://hex.pm/packages/avs_an/

**Pull request merged**
